config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "splash#index"

  resources :groups, only: [:index, :new, :create] do
    resources :operations, only: [:index, :new, :create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

    can :read, :all
    can :manage, :all, user_id: user.id
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :operations, optional: true

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :groups, optional: true

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :operations, dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end

  def index
    @categories = Group.where(user: current_user)
  end

  def create
    @group = current_user.groups.build(group_params)

    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  def new
    @group = Group.find(params[:group_id])
    @operation = Operation.new
  end

  def index
    @group = Group.find(params[:group_id])
    @operations = @group.operations.order('created_at DESC')
    @total = @operations.sum(:amount)
  end

  def create
    @group = Group.find(params[:group_id])
    @operation = current_user.operations.build(operation_params)

    if @operation.save
      @operation.groups << groups(@group)
      redirect_to group_operations_path(@group)
    else
      render :new
    end
  end

  private

  def operation_params
    params.require(:operation).permit(:name, :amount)
  end

  def groups(default_group)
    groups = [default_group]

    groups << Group.where(id: params[:operation][:group_ids])
    groups.flatten
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    redirect_to groups_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_header.html.erb
<div class="w-screen h-20 px-2 bg-bluew text-white">
  <div class= 'flex flex-row justify-between items-center px-1'>
      <%= link_to groups_path do %>
        <% if current_page? groups_path %>
          <span class="material-icons md-light md-36 mt-2">menu</span>
        
      <% else %>
        <span class="material-icons md-light md-36 mt-2">arrow_back</span>
      <% end %>
      <% end %>
    <%= button_to "Logout", destroy_user_session_path, { data: { turbo: false }, class: 'btn-primary px-1 mt-1.5 border-0', method: :delete } %>
  </div>
</div>
       
        

app/views/groups/index.html.erb
<%= render "header" %>
<h1 class="absolute top-5 left-24 title-page">CATEGORIES</h1>
<div id="categories" class='container'>
  <ul class="flex flex-col mx-auto">
    <% @categories.each do |category| %>
      <li id="#{category.name}" class="card-body text-lg">
        <%= link_to group_operations_path(category.id) do %>
          <%= category.name %>
          <span class="icon">
            <%= category.icon %>
          </span><br>
          <span class="transactions">
          <h4 class="font-bold">Total: $ <%= category.operations.sum(:amount) %></h4>
          </span>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>
<div class="btn-secondary"><%= link_to 'NEW CATEGORY', new_group_path, class: 'border border-white py-2 px-24 text-white' %></div>

app/views/groups/new.html.erb
<%= render "header" %>
<h1 class="absolute top-5 left-24 title-page">NEW CATEGORY</h1>
<%= form_with model: @group, scope: :group, url: groups_path, method: :post, data: {turbo: false}, class: "w-full flex flex-col justify-center" do |f| %>
    <div class="field">
      <%= f.label :name, class:"hidden" %>
      <%= f.text_field :name, placeholder: "Category Name", class:"input-field" %>
    </div>

    <div class="field w-90 mx-auto mt-4">
        <%= f.label :icon, 'Select Icon:', class: "mb-2 font-nova_light" %><br/>
        <%= f.select :icon, ["👔", "🎵", "🎟️", "🏆", "⚽", "🎮", "🎭", "🎨", "🎉", "🚗", "✈️", "🚢", "🚌", "🚊", "💈", "⛺", "🏨", "🏥", "🏗️​", "🏭", "🏖️", "🍽️", "🍼", "🥂", "🍔", "🍧", "🐕‍🦺​", "👩‍👧‍👧", "👨‍👩‍👧‍👦​", "🤖"], value: @group.icon, placeholder: "Select an Icon", required: true, class:"input-field" %>
    </div>
  
    <div class="actions btn-primary absolute top-5 right-3 font-nova_light">
      <%= f.submit "Add new" %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Budget</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>    
  <%= javascript_importmap_tags %>
</head>

  <body>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/operations/_header.html.erb
<div class="w-screen h-20 px-2 bg-bluew text-white">
  <div class= 'flex flex-row justify-between items-center px-1'>
  <% if current_page? new_group_operation_path(@group) %>
    <%= link_to group_operations_path(@group) do %>
       <span class="material-icons md-light md-36 mt-4">arrow_back</span>
    <% end %>
    <% else %>
    <%= link_to groups_path do %>
      <span class="material-icons md-light md-36 mt-4">arrow_back</span>
      <% end %>
      <%= button_to "Logout", destroy_user_session_path, { data: { turbo: false }, class: 'btn-primary px-1 mt-1.5', method: :delete } %>
  <% end %>
  </div>
</div>

app/views/operations/_operation.html.erb
<li class="card-body">
  <%= operation.name.capitalize %>
  - 
  $ <%= operation.amount %>
</li>

app/views/operations/index.html.erb
<%= render "header" %>
<h1 class="absolute top-5 left-28 title-page"><%= @group.name.upcase %></h1>
<h2 class="bg-white shadow-md w-full text-2x1 font-bold p-2">Total: $ <%= @total %></h2>

<ul class="flex flex-col mx-auto">
<%= render @operations %>
</ul>

<div class="btn-secondary"><%= link_to 'New Transaction', new_group_operation_path(@group), class: 'border border-white py-2 px-24 text-white' %></div>

app/views/operations/new.html.erb
<%= render "header" %>
<h1 class="absolute top-5 left-24 title-page">NEW TRANSACTION</h1>
<%= form_with model: @operation, scope: :operation, url: group_operations_path(@group), method: :post, data: {turbo: false}, class: "w-full flex flex-col justify-center" do |f| %>
    <div class="field">
      <%= f.label :name, class: "hidden" %>
      <%= f.text_field :name, placeholder: "Transaction Name", class:"input-field" %>
    </div>

    <div class="field">
        <%= f.label :amount, class: "hidden" %>
        <%= f.text_field :amount, placeholder: "Transaction Amount", class:"input-field" %>
    </div>

    <div class="grid grid-cols-2 p-3 gap-y-4 border border-neutral-200 bg-white">
        <%= f.label 'Categories' %><br />
        <%= f.collection_check_boxes :group_ids, Group.where(user: current_user).where.not(id: params[:group_id]), :id, :name, include_hidden: false %>
    </div>
    
    <div class="actions btn-primary absolute top-5 right-3 font-nova_light">
    <%= f.submit "Add new" %>
    </div>
    <% end %>

    
    
  
    
    
    
    

app/views/splash/index.html.erb
<div class="container min-h-screen max-h-screen flex flex-col justify-evenly items-center px-3">
    <h1 class="text-5xl text-center font-nova_bold text-grayw mx-auto">Smartest</h1>
    <div class="w-full mt-16">
        <div class="btn-primary block w-full "><%= link_to "Sign up", new_user_registration_path %></div>
        <div class="text-2x1 text-center font-nova_light text-grayw block w-full"><%= link_to "Log in", new_user_session_path  %></div>
     </div>
</div>